# Generated by Django 3.0.3 on 2020-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAllBooks',
            fields=[
                ('AccesssionNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Author', models.TextField()),
                ('Availability', models.TextField(blank=True)),
            ],
        ),
    ]
