# Generated by Django 3.0.3 on 2020-05-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_libraryallbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksLent',
            fields=[
                ('AccesssionNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Lent_on', models.DateField()),
                ('status', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
