# Generated by Django 3.0.3 on 2020-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_bookslent'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookavail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk', models.TextField()),
            ],
        ),
    ]
