# Generated by Django 3.0.3 on 2020-05-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_bookavail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookavail',
        ),
    ]
