# Generated by Django 3.0.3 on 2020-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_bookavail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryallbooks',
            name='Availability',
            field=models.ForeignKey(on_delete=models.SET('nan'), to='mainapp.Bookavail'),
        ),
    ]
