# Generated by Django 3.0.3 on 2020-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_bkstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslent',
            name='status',
            field=models.ForeignKey(on_delete=models.SET('Pending'), to='mainapp.bkstat'),
        ),
    ]
