# Generated by Django 3.0.3 on 2020-05-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200526_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslent',
            name='AccesssionNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.LibraryAllBooks'),
        ),
    ]
